gha: update to use oidc
redpanda-data/terraform-provider-redpanda pull request #131
Opened 2024-08-19 15:41 UTC by andrewhsu

jira: https://redpandadata.atlassian.net/browse/PESDLC-1740

this PR is primarily to use [oidc](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services) to retrieve secrets, but also other improvements along the way:
1. cleanup and fixes to github workflow syntax
2. update github workflows to use latest action versions

2024-08-19 16:57 UTC, gene-redpanda commented
Please see https://github.com/redpanda-data/terraform-provider-redpanda/pull/127/files#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34

2024-08-19 16:57 UTC, gene-redpanda requested changes
Conflicts with an existing PR on this issue

2024-08-19 17:00 UTC, andrewhsu commented
converting this PR to draft PR #127 resolves so i can rebase my changes on top of it

2024-09-12 20:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redpanda-data/terraform-provider-redpanda?pullRequest=131) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redpanda-data/terraform-provider-redpanda?pullRequest=131) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redpanda-data/terraform-provider-redpanda?pullRequest=131) it.</sub>

2024-09-23 05:11 UTC, andrewhsu commented
rebased PR on top of `main`. ready for review.

2024-09-23 18:43 UTC, ivotron approved these changes

2024-09-26 16:15 UTC, r-vasquez approved these changes

2024-09-26 16:21 UTC, gene-redpanda approved these changes
LGTM

2024-09-26 16:23 UTC, merged